### ISSUE TITLE
Fatal error on magento installation with sample data 

### ISSUE THREAD

**Issue by cebesoft** [deity-io/falcon-magento2-development#82]
On magento setup a fatal error occurs with deity falcon module:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Magento\Sales\Api\Data\OrderExtension::setMaskedId() in /var/www/vendor/deity/falcon-magento/src/Deity/Sales/Observer/Order/SetMaskedId.php:62
Stack trace:
#0 /var/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Deity\Sales\Observer\Order\SetMaskedId->execute(Object(Magento\Framework\Event\Observer))
#1 /var/www/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Deity\Sales\Observer\Order\SetMaskedId), Object(Magento\Framework\Event\Observer))
#2 /var/www/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#3 /var/www/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('sales_order_loa...', Array)
#4 /var/www/vendor/magento/framework/Model/AbstractModel.php(578): Magento\Framework\Event\Manager\Proxy->dispatch('sa in /var/www/vendor/deity/falcon-magento/src/Deity/Sales/Observer/Order/SetMaskedId.php on line 62
```

1. Use the composer.json attached
2. Run "composer install"
2. Run "php bin/magento setup:upgrade"
3. Error happens during upgrade procedure

Seems like the order observer is already active on installation of sample order data, but deity setup was not executed yet.

Workaround: remove sampledata from composer.json, do magento setup and then add and install magento sampledata again.

Composer.json:
```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        "deity/falcon-magento": "^3.0",
        "magento/module-bundle-sample-data": "100.3.*",
        "magento/module-catalog-rule-sample-data": "100.3.*",
        "magento/module-catalog-sample-data": "100.3.*",
        "magento/module-cms-sample-data": "100.3.*",
        "magento/module-configurable-sample-data": "100.3.*",
        "magento/module-customer-sample-data": "100.3.*",
        "magento/module-downloadable-sample-data": "100.3.*",
        "magento/module-grouped-product-sample-data": "100.3.*",
        "magento/module-msrp-sample-data": "100.3.*",
        "magento/module-offline-shipping-sample-data": "100.3.*",
        "magento/module-product-links-sample-data": "100.3.*",
        "magento/module-review-sample-data": "100.3.*",
        "magento/module-sales-rule-sample-data": "100.3.*",
        "magento/module-sales-sample-data": "100.3.*",
        "magento/module-swatches-sample-data": "100.3.*",
        "magento/module-tax-sample-data": "100.3.*",
        "magento/module-theme-sample-data": "100.3.*",
        "magento/module-widget-sample-data": "100.3.*",
        "magento/module-wishlist-sample-data": "100.3.*",
        "magento/product-community-edition": "2.3.0",
        "magento/sample-data-media": "100.3.*"
    },
    "require-dev": {
        "friendsofphp/php-cs-fixer": "~2.13.0",
        "lusitanian/oauth": "~0.8.10",
        "magento/magento2-functional-testing-framework": "2.3.9",
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "~3.0.0",
        "squizlabs/php_codesniffer": "3.3.1"
    },
    "conflict": {
        "gene/bluefoot": "*"
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/",
            "Zend\\Mvc\\Controller\\": "setup/src/Zend/Mvc/Controller/"
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "version": "2.3.0",
    "minimum-stability": "stable",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "extra": {
        "magento-force": "override"
    }
}
```

**Comment by cane-lagerwaard** [comment]
@cebesoft are you still able to reproduce this issue?
